### ISSUE TITLE
How to fill the empty space with buttons?

### ISSUE THREAD

**Issue by Jacko120** [Rodiii/flutter_firebase_picture_uploader#11]
Heya, thank you for making this package.

Any ideas on how I would be able to fill the empty space with upload buttons which get replaced with the photos once selected? 

Like this for example. Thank you

![example](https://user-images.githubusercontent.com/11403326/104563510-a7064100-5641-11eb-9323-ee405ef53e80.png)

**Comment by Rodiii** [comment]
Hi @Jacko120, 
Currently, this isn't possible. Anyhow, this could be introduced as a new feature. 
=> By e.g. introducing a parameter for PictureUploadWidget which says "displayPossiblePlaceholders". If activated, all placeholders to the max upload images could be displayed.

Feel free to create a pull request if you have time to code such a feature.

Best,
Christoph
