### ISSUE TITLE
Not up to date with Firestore lastest 2021 version

### ISSUE THREAD

**Issue by davemg3** [Rodiii/flutter_firebase_picture_uploader#12]
Hi, thanks for these nice features
I gave a shot to your sample app to check if library was still up to date and i noticed it cannot work with new flutter project as in library, dependencies cannot resolve with :
  firebase_core: ^0.7.0
  firebase_storage: "^7.0.0"
  firebase_auth: ^0.20.0+1

By Dowloading your library and testing it with new firebase lib, i see it is ok.

Can you please update your dependencies?
Thanks again

**Comment by Rodiii** [comment]
Hi @davemg3, could you please try version 1.2.1? I just upgraded the package.

**Comment by davemg3** [comment]
Thanks @Rodiii for your reactivity, this is working...
A minor comment. The following should be considered for instructions for Android : 

`  <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>`

Otherwise people will see call to the lib with cropping option activated  failing silently

Thanks

**Comment by davemg3** [comment]
I noticed also in library, text and icon are not options. You cannot remove one or the other .

It would be nice to put a check in `getNewImageButton()` method so as to remove the space taken if users choose a button with name or a button with image or both
