### ISSUE TITLE
loading when uploading

### ISSUE THREAD

**Issue by glennmichaelmejias** [Rodiii/flutter_firebase_picture_uploader#13]
why i see loading when choosing an image and then crop and right after i check it its load for 1 seconds even if my internet is so fast? is there a timeout on the plugin? thank you so much for this great plugin also!

**Comment by Rodiii** [comment]
Hi @glennmichaelmejias, 

I guess this happens because of some delays during the firebase storage upload.
I don't see this as issue of this plugin.

Anyhow, if you find out that it is really an issue with this plugin, feel free to create a PR.

Best,
Christoph
