### ISSUE TITLE
firebase_picture_uploader need to be updated with image_picker  ^0.7.2+1 

### ISSUE THREAD

**Issue by davemg3** [Rodiii/flutter_firebase_picture_uploader#14]
firebase_picture_uploader ^1.2.1 requires image_picker 0.6.7+22   but currently image_picker has been updated to ^0.7.2+1 so as to be compatible now with  **flutter_plugin_android_lifecycle: ^2.0.0**.

Due to major ugrade recently on Flutter, could you please upgrade your package?

Thank you @Rodiii

**Comment by Rodiii** [comment]
I've updated all dependencies, thanks for informing me.
=>  https://pub.dev/packages/firebase_picture_uploader/versions/1.2.2

Best,
Christoph
