### ISSUE TITLE
Compatibility with flutter null safety libraries using mainly rxdart ^0.26.0

### ISSUE THREAD

**Issue by davemg3** [Rodiii/flutter_firebase_picture_uploader#15]
Finally following dependencies has been updated by their owners :
cached_network_image: ^3.0.0 which depends on
flutter_cache_manager: ^3.0.0 which depends on
=> rxdart ^0.26.0

So could you please give us an update?

Thank you @Rodiii

**Comment by Rodiii** [comment]
Just upgraded cached_network_image, thanks for letting me know!
v1.2.3
