### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Matthuffy** [Rodiii/flutter_firebase_picture_uploader#3]
Because every version of firebase_picture_uploader depends on firebase_storage ^3.1.5 and firefly depends on firebase_storage ^4.0.0, firebase_picture_uploader is forbidden.

**Comment by Rodiii** [comment]
Thanks for the hint. I updated the dependencies, also in pub.dev

Have fun!

**Comment by Matthuffy** [comment]
Few more edits I noticed, will add after to let you see and maybe accept.
Bit busy with a project for now
