### ISSUE TITLE
Access Link

### ISSUE THREAD

**Issue by praveengupta0895** [Rodiii/flutter_firebase_picture_uploader#4]
How do I get the access link of the uploaded image, I want to add the access link to database at the same time.

**Comment by Rodiii** [comment]
Via onPicturesChange you get a link to the StorageReference:
``
PictureUploadWidget(
            onPicturesChange: profilePictureCallback,
            initialImages: _profilePictures,
            settings: PictureUploadSettings(onErrorFunction: onErrorCallback),
            buttonStyle: const PictureUploadButtonStyle(),
            buttonText: 'Upload Picture',
            enabled: true,
          ),
``

Please refer to the firebase storage documentation to find out how you can generate a download link afterwards.
