### ISSUE TITLE
PictureUploadWidget is constant

### ISSUE THREAD

**Issue by 4mitabh** [Rodiii/flutter_firebase_picture_uploader#5]
Can we make PictureUploadWidget.settings not be a constant ?
This way an app can dynamically set upload directories. For example, different users may have different non-constant profile paths.

**Comment by Rodiii** [comment]
Most of the parameters are non-constant in firebase_picture_uploader version 1.2.0, now. Thanks for the hint.

**Comment by 4mitabh** [comment]
Awesome!!!
Many thanks.
