### ISSUE TITLE
Add support for buckets

### ISSUE THREAD

**Issue by dixyantar** [Rodiii/flutter_firebase_picture_uploader#7]
As such, the plugin uses the default Firestore instance. Users would want to specify the bucket name instead of having to implement own upload and download methods. 
FirebaseStorage _storage = bucket==null?Firestore.instance:Firestore(storageBucket:bucket)

**Comment by Rodiii** [comment]
Just added this in firebase_picture_uploader version 1.2.0:

PictureUploadWidget is having a storageInstance parameter now.
```
  PictureUploadWidget(
      {...
      FirebaseStorage storageInstance,
      })
      : ...
        storageInstance = storageInstance ?? FirebaseStorage.instance;
```
