### ISSUE TITLE
Disable cropper

### ISSUE THREAD

**Issue by rahulserver** [Rodiii/flutter_firebase_picture_uploader#8]
Currently the plugin takes to the image cropper on upload. i would prefer this to be disabled. Is it possible?

**Comment by Rodiii** [comment]
Just added this in firebase_picture_uploader version 1.2.0.

Just look for enableCropping in PictureUploadSettings:
```
PictureUploadSettings(
                imageManipulationSettings: const ImageManipulationSettings(
                    enableCropping: true))
```
