### ISSUE TITLE
FirebaseCoreInternal.h' file not found Error happened.

### ISSUE THREAD

**Issue by kode-soar** [Rodiii/flutter_firebase_picture_uploader#9]
/Users/****/****/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/FIRStorageReference.m:34:9: fatal error: 'FirebaseCore/Sources/Private/FirebaseCoreInternal.h' file not found
    #import "FirebaseCore/Sources/Private/FirebaseCoreInternal.h"

I used this package in the app I'm making, and the error above appeared.
Just in case, I tried to build example's code in the repository, but the same error occurred.
How can we solve this?

**Comment by Rodiii** [comment]
Hi @kode-soar, could you please upload a full stack trace?
Maybe a „pod upgrade“ within the iOS directory could help. I will have a further look on that this weekend.

**Comment by kode-soar** [comment]
Thank you.
pod deintegrate
pod cache clean --all
pod install

work well!

Sorry :D
